### ISSUE TITLE
如何在几秒中生成的?

### ISSUE THREAD

**Issue by LeoLeeTech** [CrazyDudo/markdown-editor#1]
我是v2ex的发帖者, 看你一直没回复就到这来了, 实在是好奇

我是提前各种技术选型,甚至跑起来几个demo,  选到了electron-vite, 加上我用过markdown-it, 就开始集成这个
集成过程中, 用的是 gpt4o 遇到什么问题就问他，可费了不少劲, 2天才算把这事成这样(读文件并渲染)

我猜测你是对前端熟悉, 也是用脚手架生成的项目, 但是
- 一个项目中会有很多文件
- 每个文件都在相应的位置
- 每个文件中都有不同的内容

请问你用的是什么模型？
提示词让他干什么？  
他做了那些事?

**Comment by CrazyDudo** [comment]
1. https://bolt.new/
2. 做一个markdown 编辑器；
3. 生成代码并运行；
